export enum TIKTOK_EVENT_ENUM {
  COMMENT = 'COMMENT',
  LIKE = 'LIKE',
  SHARE = 'SHARE',
  JOIN = 'JOIN',
  FOLLOW = 'FOLLOW',
  GIFT = 'GIFT',
  GIFT_COMBO = 'GIFT_COMBO',
  VIEWER_INFO = 'VIEWER_INFO',
}
